### ISSUE TITLE
Compile With LLVM Clang

### ISSUE THREAD

**Issue by onthegrid007** [luxonis/XLink#12]
Hi, even though I have been using github for some 5 years now, I still have not once done a pull-request. Meaning I am not looking for any credit, hell I just want the damn thing fixed so I don't have to keep providing another flag to depthai-core when building to tell it where the fixed xlink library is.

In the file pc/protocols/tcpip_host.h there is the function declaration for the public close socket function. The param is int socketfd, but the definition in tcpip_host.c has SOCKET sock as its param. I do not know if SOCKET is supposed to macro to int but just fixing that one thing allows the static lib to be built using the latest LLVM Clang Binarys on Windows. I am going to check now if depthai-core can also work out of the box now with LLVM Clang, if not, I will also do a similar message on that repo stating my findings so someone else can fix that. Then you can promote LLVM Clang as a working toolchain. ;)

p.s. yes I would also be greatful for some links on where to learn pull-requests, creation, management, and whatever else so I don't have to keep doing it this way...

Many thanks,
-Peter F

**Comment by themarpe** [comment]
@onthegrid007 thanks for the report. This seems to be the same issue as a MinGW one.

WRT PRs, feel free to fork the repository, create a branch with commited changes and then open the pull request here on GitHub.
A helpful link would be: https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request

Sorry for this mistake affecting the clang in Windows build.
Right now do CI for MSVC (Win), Clang (macOS) and GCC (Ubuntu). If you wish, you can create a separate PR for Clang in Windows CI, which would help future changes not break building on this compiler/OS combination.

Same idea applies to depthai-core.

That said, the change is quite small in this case and I can push a fix for it around today/tomorrow.
Let me know if you'd rather have me apply the fix. (But CI additions for future are still very welcome:) )

**Comment by alex-luxonis** [comment]
Mentioning the other issue for reference: https://github.com/luxonis/depthai-core/issues/186
