### ISSUE TITLE
xlink contribution branch unclear (develop is very behind master)

### ISSUE THREAD

**Issue by diablodale** [luxonis/XLink#28]
I have a PR ready for xlink, but the branch on which to submit it is unclear.
`develop` is usually the branch to use for Luxonis projects.
But `develop` is many commits behind `master`. So many that it is unreliable to use for a PR.

What should I do @themarpe ?

**Comment by themarpe** [comment]
@diablodale Feel free to point to `master` if the changes are "final", or to `develop` if requires a bit more time to soak in or awaits some other change.

**Comment by alex-luxonis** [comment]
Indeed `develop` was a little behind `master`, but was possible to do a fast-forward merge.
I just pushed, they should be even at this time.

**Comment by diablodale** [comment]
thanks. closing.
