### ISSUE TITLE
Clang immintrin bug

### ISSUE THREAD

**Issue by onthegrid007** [luxonis/XLink#80]
HI I have been trying to deduce this bug from the [depthai-core](https://github.com/luxonis/depthai-core) library and found out that it is a simple fix but do not know how to make a pull request...

In the file:
XLink/src/pc/protocols/usb_host.cpp

The std headers just need to be moved to the top of the file for [this ](https://github.com/llvm/llvm-project/issues/91415) bug to be fixed... I assumed it was a clang bug but it turns out its an order of header bug.

This would make the xlink library clang compatible if this single issue is fixed

**Comment by themarpe** [comment]
@onthegrid007 you may post the diff here and I can apply the fix
Otherwise WRT making a PR, you can: 
 - Fork the XLink repository
 - commit the change that fixes it to your fork
 - click New Pull Request under Luxonis XLink repo and select your fork/master and our master branch

**Comment by onthegrid007** [comment]
I will follow this this weekend, middle of school atm
